/* eslint-disable camelcase */

import * as Yup from "yup";

export const encounterFormSchema = Yup.object({
  first_name: Yup.string().required("first Name is required"),
  last_name: Yup.string(),
  location: Yup.string(),
  date_of_birth: Yup.string(),
  date_of_service: Yup.string(),
  phone_no: Yup.string(),
  email: Yup.string(),
  history_of_present: Yup.string(),
  medical_history: Yup.string(),
  medications: Yup.string(),
  allergies: Yup.string(),
  temperature: Yup.string(),
  heart_rate: Yup.string(),
  respiratory_rate: Yup.string(),
  blood_pressure_1: Yup.string(),
  blood_pressure_2: Yup.string(),
  o2: Yup.string(),
  pain: Yup.string(),
  heent: Yup.string(),
  cv: Yup.string(),
  chest: Yup.string(),
  abd: Yup.string(),
  extr: Yup.string(),
  skin: Yup.string(),
  neuro: Yup.string(),
  other: Yup.string(),
  diagnosis: Yup.string(),
  treatment_plan: Yup.string(),
  medication_dispensed: Yup.string(),
  procedures: Yup.string(),
  follow_up: Yup.string(),
});
