export const AppRoutes = {
  LOGIN: "/login",
  FORGOTPASS: "/forgot-password",
  RESETPASS: "/resetPassword/:reset_token",
  DASHBOARD: "/dashboard",
  RESERVATION: "/dashboard/viewreservation",
  NOTES: "/dashboard/viewnotes",
  VIEWUPLOAD: "/dashboard/viewupload",
  ORDER: "/dashboard/order",
  CLOSECASE: "/dashboard/closecase",
  MYPROFILE: "/myprofile",
  PROVIDER: "/provider",
  EDITACCOUNT: "/editAccount",
  ACCESSACCOUNT: "/acessAccount",
  CREATEACCESS: "/acessAccount/createAccess",
};
