export const rows = [
  {
    id: 1,
    patientName: "Alice Johnson",
    requestor: "Dr. Smith",
    dateOfService: "2024-03-28",
    closeCaseDate: "2024-04-02",
    email: "alice@example.com",
    phoneNumber: "555-123-4567",
    address: "123 Main St",
    zip: "12345",
    requestStatus: "Completed",
    physician: "Dr. Brown",
    physicianNote: "Patient responded well to treatment.",
    cancelledByProviderNote: null,
    adminNote: "Insurance approval pending.",
    patientNote: "Mild discomfort after procedure.",
  },
  {
    id: 2,
    patientName: "Bob Williams",
    requestor: "Nurse Johnson",
    dateOfService: "2024-03-30",
    closeCaseDate: null,
    email: "bob@example.com",
    phoneNumber: "555-987-6543",
    address: "456 Elm St",
    zip: "54321",
    requestStatus: "In Progress",
    physician: "Dr. Lee",
    physicianNote: "Further tests needed.",
    cancelledByProviderNote: null,
    adminNote: "Awaiting lab results.",
    patientNote: "No significant symptoms.",
  },
  {
    id: 3,
    patientName: "Carol Adams",
    requestor: "Dr. White",
    dateOfService: "2024-03-25",
    closeCaseDate: "2024-04-01",
    email: "carol@example.com",
    phoneNumber: "555-555-5555",
    address: "789 Oak Ave",
    zip: "67890",
    requestStatus: "Completed",
    physician: "Dr. Green",
    physicianNote: "Excellent progress observed.",
    cancelledByProviderNote: null,
    adminNote: "Billing details verified.",
    patientNote: "Feeling much better.",
  },
  {
    id: 4,
    patientName: "David Clark",
    requestor: "Dr. Johnson",
    dateOfService: "2024-03-29",
    closeCaseDate: null,
    email: "david@example.com",
    phoneNumber: "555-777-8888",
    address: "567 Maple Rd",
    zip: "45678",
    requestStatus: "Pending",
    physician: "Dr. Adams",
    physicianNote: "Awaiting test results.",
    cancelledByProviderNote: null,
    adminNote: "Follow-up appointment scheduled.",
    patientNote: "No major concerns.",
  },
  {
    id: 5,
    patientName: "Eva Garcia",
    requestor: "Nurse Brown",
    dateOfService: "2024-03-31",
    closeCaseDate: null,
    email: "eva@example.com",
    phoneNumber: "555-222-3333",
    address: "345 Pine Ln",
    zip: "23456",
    requestStatus: "In Progress",
    physician: "Dr. Miller",
    physicianNote: "Monitoring progress closely.",
    cancelledByProviderNote: null,
    adminNote: "Insurance pre-authorization requested.",
    patientNote: "Slight improvement.",
  },
];

export const columns = [
  {
    id: "patient_name",
    label: "Patient Name",
  },
  {
    id: "requestor",
    label: "Requestor",
  },
  {
    id: "date_of_service",
    label: "Date Of Service",
  },
  {
    id: "closed_date",
    label: "Close Case Date",
  },
  {
    id: "email",
    label: "Email",
  },
  {
    id: "phone_no",
    label: "Phone Number",
  },
  {
    id: "address",
    label: "Address",
  },
  {
    id: "zip",
    label: "Zip",
  },
  {
    id: "request_status",
    label: "Request Status",
  },
  {
    id: "physician",
    label: "Physician",
  },
  {
    id: "physicianNote",
    label: "Physician Note",
  },
  {
    id: "cancelledByProviderNote",
    label: "Cancelled By Provider Note",
  },
  {
    id: "admin_notes",
    label: "Admin Note",
  },
  {
    id: "patient_notes",
    label: "Patient Note",
  },
  {
    id: "delete",
    label: "Delete Permanently",
  },
];
